### ISSUE TITLE
Plugin does not reconnect

### ISSUE THREAD

**Issue by schw4rzlicht** [bitfocus/companion-module-generic-ssh#4]
Hey there!

When e.g. rebooting a remote device, the SSH connection is not re-established. Would be good if that'd be the case. Our use-case is to reboot headless media servers in a show environment from another headless server that has Companion running.

Thanks!

**Comment by Jibun-no-Kage** [comment]
Looking for answer to this as well, comparable use case, anyone one actively supporting this module?  Just asking, since this issue was posted some time ago.

**Comment by cyberblaststudios** [comment]
I will try my best to get to this within the next several days. Thank you for your patience!

**Comment by Jibun-no-Kage** [comment]
Thank you very much for addressing this request.  Always appreciate when modules are supported!

**Comment by cyberblaststudios** [comment]
In release v1.3.0 (https://github.com/bitfocus/companion-module-generic-ssh/releases/tag/v1.3.0) I have added a re-connect feature that will attempt to reconnect SSH every second if it loses connection by receiving a TCP reset from the server, or fails to connect to the server. This build should be included in the betas in the near future, and eventually the stable version.

I will close this issue now that I have created the release with the fix. If you still have trouble, feel free to comment here.

**Comment by Jibun-no-Kage** [comment]
Yeah, will let you know.  Thanks again, I know time is limited, but just the same, appreciate you supporting the module.  Just had a thought... maybe in the future... make this reconnect a configurable option?  Meaning it can be toggled on or off?   Just was thinking about possible use cases.  Or it already is per your update?

**Comment by cyberblaststudios** [comment]
> Yeah, will let you know.  Thanks again, I know time is limited, but just the same, appreciate you supporting the module.  Just had a thought... maybe in the future... make this reconnect a configurable option?  Meaning it can be toggled on or off?   Just was thinking about possible use cases.  Or it already is per your update?

Right now, it's not a configurable option to reconnect. I'm curious what a use case would be for that. I am all ears on suggestions.

Thanks!
